version: '3.8'

services:
  zimusha-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zimusha-frontend
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://185.209.228.74:8080/api
      - NEXT_PUBLIC_BACKEND_URL=http://185.209.228.74:8080
      - NEXT_PUBLIC_APP_NAME=ZIMUSHA
      - NEXT_PUBLIC_APP_URL=https://ubiqent.com
      - NEXT_PUBLIC_FRONTEND_URL=https://ubiqent.com
      - NEXT_TELEMETRY_DISABLED=1
    networks:
      - zimusha-network

  nginx:
    image: nginx:latest
    container_name: zimusha-nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - zimusha-frontend
    networks:
      - zimusha-network

  certbot:
    image: certbot/certbot
    container_name: zimusha-certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
    networks:
      - zimusha-network

networks:
  zimusha-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
