// lib/mock-data.ts

export const mockContent = [
  {
    id: "1",
    type: "movie",
    title: "The Last Kingdom",
    thumbnail: "https://images.unsplash.com/photo-1524985069026-dd778a71c7b4?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    description: "A warrior fights to claim his birthright.",
    genre: "Action",
    year: 2024,
    rating: "PG-13",
    duration: "2h 12m",
    cast: ["Actor A", "Actor B"],
    crew: ["Director X", "Writer Y"],
    ageLimit: "13+",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "2",
    type: "movie",
    title: "Rise of Legends",
    thumbnail: "https://images.unsplash.com/photo-1517602302552-471fe67acf66?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    description: "Heroes gather to face a looming threat.",
    genre: "Adventure",
    year: 2023,
    rating: "PG-13",
    duration: "1h 58m",
    cast: ["Actor C", "Actor D"],
    crew: ["Director Z", "Producer K"],
    ageLimit: "13+",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "3",
    type: "series",
    title: "Zimushaland",
    thumbnail: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: Welcome to Zimushaland",
        description: "The journey begins in the magical land of Zimushaland.",
      },
      {
        title: "Episode 2: The Rising Conflict",
        description: "Tensions rise as new challenges appear.",
      },
      {
        title: "Episode 3: The Hidden Power",
        description: "A secret power begins to emerge among the heroes.",
      },
    ],
    description: "An epic saga across mystical lands.",
    genre: "Fantasy",
    year: 2025,
    rating: "TV-14",
    duration: "8 eps",
    crew: ["Showrunner Q"],
    ageLimit: "14+",
  },
  {
    id: "4",
    type: "series",
    title: "Code Warriors",
    thumbnail: "https://images.unsplash.com/photo-1518779578993-ec3579fee39f?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: The Call to Code",
        description: "A team of young coders is called to defend the digital realm.",
      },
      {
        title: "Episode 2: Debugging the Enemy",
        description: "The warriors face their first big challenge in the system.",
      },
      {
        title: "Episode 3: Power of Open Source",
        description: "An unexpected ally joins the fight for freedom.",
      },
    ],
    description: "A tech squad battles digital foes.",
    genre: "Sci-Fi",
    year: 2022,
    rating: "TV-13",
    duration: "10 eps",
    crew: ["Showrunner W"],
    ageLimit: "13+",
  },
  // 🔥 New Content
  {
    id: "9",
    type: "movie",
    title: "Echoes of the Savannah",
    thumbnail: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    description: "Nature’s beauty and danger collide.",
    genre: "Documentary",
    year: 2021,
    rating: "PG",
    duration: "1h 22m",
    crew: ["Director N"],
  },
  {
    id: "10",
    type: "series",
    title: "Digital Shadows",
    thumbnail: "https://images.unsplash.com/photo-1488229297570-58520851e868?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: Into the Net",
        description: "A hacker discovers a dark world hidden inside the web.",
      },
      {
        title: "Episode 2: Ghost Protocol",
        description: "Anonymity comes with a dangerous price.",
      },
      {
        title: "Episode 3: Breaking Firewalls",
        description: "The ultimate showdown against cyber overlords begins.",
      },
    ],
    description: "A hacker dives deep into the darknet.",
    genre: "Thriller",
    year: 2020,
    rating: "TV-MA",
    duration: "6 eps",
    crew: ["Showrunner T"],
    ageLimit: "18+",
  },
  {
    id: "11",
    type: "movie",
    title: "Kingdom of Stone",
    thumbnail: "https://images.unsplash.com/photo-1526318472351-c75fcf070305?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    description: "A nation rises from ruins.",
    genre: "Drama",
    year: 2024,
    rating: "R",
    duration: "2h 5m",
    crew: ["Director A1"],
    ageLimit: "18+",
  },
  {
    id: "12",
    type: "series",
    title: "The Great Migration",
    thumbnail: "https://images.unsplash.com/photo-1456926631375-92c8ce872def?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: The Journey Begins",
        description: "Animals set off on their epic migration across Africa.",
      },
      {
        title: "Episode 2: Predators and Prey",
        description: "Survival becomes a game of wits and instincts.",
      },
      {
        title: "Episode 3: The Final Crossing",
        description: "The herd faces the deadliest challenge at the river crossing.",
      },
    ],
    description: "The epic odyssey of wildlife.",
    genre: "Nature",
    year: 2019,
    rating: "TV-PG",
    duration: "5 eps",
    crew: ["Director B1"],
  },
  // Extra dummy entries for grid scrolling
  ...Array.from({ length: 30 }).map((_, i) => ({
    id: String(200 + i),
    type: "movie" as const,
    title: `Sample Movie ${i + 1}`,
    thumbnail: `https://picsum.photos/seed/movie_${i}/600/400`,
    isPremium: i % 3 === 0,
    description: "Sample description for demo content.",
    genre: ["Action", "Drama", "Comedy", "Thriller"][i % 4],
    year: 2015 + (i % 11),
    rating: ["G", "PG", "PG-13", "R"][i % 4],
    duration: `${90 + (i % 40)}m`,
    videoUrl: i % 5 === 0 ? "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" : undefined,
  })),
];

export const mockTrending = [
  {
    id: "5",
    type: "movie",
    title: "Shadows of Time",
    thumbnail: "https://images.unsplash.com/photo-1498709112912-9be3173d30be?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    description: "Time bends to a willful hero",
    genre: "Sci-Fi",
    year: 2023,
    rating: "PG-13",
    duration: "1h 45m",
  },
  {
    id: "6",
    type: "series",
    title: "Future Chronicles",
    thumbnail: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: Tomorrow Begins",
        description: "The world awakens to new futuristic possibilities.",
      },
      {
        title: "Episode 2: Breaking the Boundaries",
        description: "Humans test the limits of science and technology.",
      },
      {
        title: "Episode 3: The Unknown Beyond",
        description: "The team faces unexpected consequences of their inventions.",
      },
    ],
  },
  // 🔥 Extra trending
  {
    id: "13",
    type: "movie",
    title: "Blood Moon Rising",
    thumbnail: "https://images.unsplash.com/photo-1498081959737-f3ba1af08103?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    description: "A night of omens.",
    genre: "Horror",
    year: 2022,
    rating: "R",
    duration: "1h 39m",
  },
  {
    id: "14",
    type: "series",
    title: "Warriors of Tomorrow",
    thumbnail: "https://images.unsplash.com/photo-1520975938851-5b27c3b53934?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Awakening",
        description: "A group of rebels rise against futuristic oppressors.",
      },
      {
        title: "Episode 2: Fire and Steel",
        description: "The rebels clash with powerful AI-driven armies.",
      },
      {
        title: "Episode 3: The Last Stand",
        description: "Humanity’s fate lies in the balance.",
      },
    ],
  },
];

export const mockRecommended = [
  {
    id: "7",
    type: "series",
    title: "Legends of Africa",
    thumbnail: "https://images.unsplash.com/photo-1505925456693-124134d66749?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Ancient Origins",
        description: "Uncovering the hidden history of African heroes.",
      },
      {
        title: "Episode 2: Kingdoms Rising",
        description: "The great civilizations of Africa rise and prosper.",
      },
      {
        title: "Episode 3: Legacy of Warriors",
        description: "Stories of courage and resilience echo through time.",
      },
    ],
  },
  {
    id: "8",
    type: "movie",
    title: "Silent Horizon",
    thumbnail: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    description: "A quiet storm brews beyond the skyline.",
    genre: "Mystery",
    year: 2021,
    rating: "PG-13",
    duration: "2h 1m",
  },
  // 🔥 Extra recommended
  {
    id: "15",
    type: "series",
    title: "Desert Mysteries",
    thumbnail: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?w=1200&auto=format&fit=crop&q=60",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: Sands of Time",
        description: "Explorers uncover secrets buried deep beneath the desert.",
      },
      {
        title: "Episode 2: Oasis of Hope",
        description: "A forgotten tribe holds the key to survival.",
      },
      {
        title: "Episode 3: Storm of Destiny",
        description: "The desert unleashes its fury in an epic climax.",
      },
    ],
  },
  {
    id: "16",
    type: "movie",
    title: "Crimson River",
    thumbnail: "https://images.unsplash.com/photo-1495567720989-cebdbdd97913?w=1200&auto=format&fit=crop&q=60",
    isPremium: false,
    description: "A town’s secrets flow like water.",
    genre: "Crime",
    year: 2018,
    rating: "R",
    duration: "1h 48m",
  },
];
