// lib/mock-data.ts

export const mockContent = [
  {
    id: "1",
    type: "movie",
    title: "Hearts of Africa",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A powerful drama showcasing the resilience and beauty of African communities through generations of storytelling.",
    genre: "Drama",
    genres: ["Drama", "Diaspora", "Classics"],
    year: 2024,
    rating: "PG-13",
    duration: "2h 15m",
    cast: ["Thandiwe Newton", "Chiwetel Ejiofor", "Lupita Nyong'o"],
    crew: ["Director Ava DuVernay", "Producer Will Packer"],
    ageLimit: "13+",
    language: "English",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "2",
    type: "movie",
    title: "Chief Ben: The Legacy",
    thumbnail: "/thumnails/chief_ben.jpeg",
    isPremium: true,
    description: "The inspiring true story of Chief Ben, a traditional leader who bridged ancient wisdom with modern governance in colonial Africa.",
    genre: "Documentary",
    genres: ["Documentary", "Exclusive", "Classics"],
    year: 2023,
    rating: "PG",
    duration: "1h 45m",
    cast: ["Documentary Narration"],
    crew: ["Director Raoul Peck", "Producer Stephanie Allain"],
    ageLimit: "All Ages",
    language: "English",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "3",
    type: "movie",
    title: "More Salah: The Football King",
    thumbnail: "/thumnails/more_salah.jpeg",
    isPremium: false,
    description: "Follow the incredible journey of Africa's football legend as he rises from humble beginnings to international stardom.",
    genre: "Sports",
    genres: ["Sports", "Documentary", "Platform Originals"],
    year: 2024,
    rating: "PG",
    duration: "1h 52m",
    cast: ["Mohamed Salah", "Various Athletes"],
    crew: ["Director Antoine Fuqua", "Producer LeBron James"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "4",
    type: "movie",
    title: "Mutukudzi: The Voice of Zimbabwe",
    thumbnail: "/thumnails/mutukudzi.jpeg",
    isPremium: true,
    description: "A musical biography celebrating the life and legacy of Oliver Mutukudzi, Zimbabwe's beloved musician and cultural icon.",
    genre: "Music",
    genres: ["Music", "Documentary", "Diaspora"],
    year: 2023,
    rating: "PG",
    duration: "2h 8m",
    cast: ["Oliver Mutukudzi", "Various Musicians"],
    crew: ["Director Tsitsi Dangarembga", "Producer Danai Gurira"],
    ageLimit: "All Ages",
    language: "Shona",
  },
  {
    id: "5",
    type: "series",
    title: "African Real Estate Empire",
    thumbnail: "/thumnails/real_estate.jpeg",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Building Dreams in Lagos",
        description: "Young entrepreneurs transform Nigeria's real estate landscape with innovative housing solutions.",
      },
      {
        title: "Episode 2: Cape Town's Golden Mile",
        description: "Luxury developments meet community needs in South Africa's most prestigious locations.",
      },
      {
        title: "Episode 3: Nairobi Rising",
        description: "Kenya's capital becomes a hub for sustainable urban development.",
      },
      {
        title: "Episode 4: Accra's New Horizon",
        description: "Ghana's real estate boom attracts international investors and diaspora returnees.",
      },
    ],
    description: "A reality series following Africa's most ambitious real estate projects and the visionaries behind them.",
    genre: "Real Estate",
    genres: ["Real Estate", "Reality", "Lifestyle"],
    year: 2024,
    rating: "TV-PG",
    duration: "8 eps",
    crew: ["Producer Issa Rae", "Director Ryan Coogler"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "6",
    type: "movie",
    title: "Victoria Falls: Wonder of the World",
    thumbnail: "/thumnails/vic_falls.jpeg",
    isPremium: false,
    description: "An breathtaking documentary exploring the natural wonder of Victoria Falls and its significance to local communities.",
    genre: "Documentary",
    genres: ["Documentary", "Adventure", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 28m",
    cast: ["David Attenborough (Narrator)"],
    crew: ["Director James Cameron", "Producer National Geographic"],
    ageLimit: "All Ages",
    language: "English",
  },
  // Additional African-themed content
  {
    id: "7",
    type: "series",
    title: "Ubuntu: Stories of Humanity",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: The Philosophy of Ubuntu",
        description: "Exploring the African philosophy that emphasizes our shared humanity.",
      },
      {
        title: "Episode 2: Community Healing",
        description: "How traditional African healing practices bring communities together.",
      },
      {
        title: "Episode 3: Modern Ubuntu",
        description: "Ubuntu principles in contemporary African leadership and business.",
      },
    ],
    description: "A philosophical journey through African wisdom and community values.",
    genre: "Lifestyle",
    genres: ["Lifestyle", "Documentary", "Diaspora"],
    year: 2023,
    rating: "TV-PG",
    duration: "6 eps",
    crew: ["Director Wanuri Kahiu", "Producer Lupita Nyong'o"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "8",
    type: "movie",
    title: "Afrimation: The New Wave",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A groundbreaking animated film showcasing African folklore through cutting-edge animation techniques.",
    genre: "Afrimation",
    genres: ["Afrimation", "Kids", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 35m",
    cast: ["Lupita Nyong'o", "Michael B. Jordan", "Danai Gurira"],
    crew: ["Director Peter Ramsey", "Producer Kenya Barris"],
    ageLimit: "All Ages",
    language: "English",
  },
  // Extra dummy entries for grid scrolling
  ...Array.from({ length: 30 }).map((_, i) => ({
    id: String(200 + i),
    type: "movie" as const,
    title: `Sample Movie ${i + 1}`,
    thumbnail: `https://picsum.photos/seed/movie_${i}/600/400`,
    isPremium: i % 3 === 0,
    description: "Sample description for demo content.",
    genre: ["Action", "Drama", "Comedy", "Thriller"][i % 4],
    year: 2015 + (i % 11),
    rating: ["G", "PG", "PG-13", "R"][i % 4],
    duration: `${90 + (i % 40)}m`,
    videoUrl: i % 5 === 0 ? "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" : undefined,
  })),
];

export const mockTrending = [
  {
    id: "1",
    type: "movie",
    title: "Hearts of Africa",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A powerful drama showcasing the resilience and beauty of African communities through generations of storytelling.",
    genre: "Drama",
    genres: ["Drama", "Diaspora", "Classics"],
    year: 2024,
    rating: "PG-13",
    duration: "2h 15m",
    language: "English",
  },
  {
    id: "3",
    type: "movie",
    title: "More Salah: The Football King",
    thumbnail: "/thumnails/more_salah.jpeg",
    isPremium: false,
    description: "Follow the incredible journey of Africa's football legend as he rises from humble beginnings to international stardom.",
    genre: "Sports",
    genres: ["Sports", "Documentary", "Platform Originals"],
    year: 2024,
    rating: "PG",
    duration: "1h 52m",
    language: "English",
  },
  {
    id: "6",
    type: "movie",
    title: "Victoria Falls: Wonder of the World",
    thumbnail: "/thumnails/vic_falls.jpeg",
    isPremium: false,
    description: "An breathtaking documentary exploring the natural wonder of Victoria Falls and its significance to local communities.",
    genre: "Documentary",
    genres: ["Documentary", "Adventure", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 28m",
    language: "English",
  },
  {
    id: "5",
    type: "series",
    title: "African Real Estate Empire",
    thumbnail: "/thumnails/real_estate.jpeg",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Building Dreams in Lagos",
        description: "Young entrepreneurs transform Nigeria's real estate landscape with innovative housing solutions.",
      },
      {
        title: "Episode 2: Cape Town's Golden Mile",
        description: "Luxury developments meet community needs in South Africa's most prestigious locations.",
      },
      {
        title: "Episode 3: Nairobi Rising",
        description: "Kenya's capital becomes a hub for sustainable urban development.",
      },
      {
        title: "Episode 4: Accra's New Horizon",
        description: "Ghana's real estate boom attracts international investors and diaspora returnees.",
      },
    ],
    description: "A reality series following Africa's most ambitious real estate projects and the visionaries behind them.",
    genre: "Real Estate",
    genres: ["Real Estate", "Reality", "Lifestyle"],
    year: 2024,
    rating: "TV-PG",
    duration: "8 eps",
    language: "English",
  },
];

export const mockRecommended = [
  {
    id: "2",
    type: "movie",
    title: "Chief Ben: The Legacy",
    thumbnail: "/thumnails/chief_ben.jpeg",
    isPremium: true,
    description: "The inspiring true story of Chief Ben, a traditional leader who bridged ancient wisdom with modern governance in colonial Africa.",
    genre: "Documentary",
    genres: ["Documentary", "Exclusive", "Classics"],
    year: 2023,
    rating: "PG",
    duration: "1h 45m",
    language: "English",
  },
  {
    id: "4",
    type: "movie",
    title: "Mutukudzi: The Voice of Zimbabwe",
    thumbnail: "/thumnails/mutukudzi.jpeg",
    isPremium: true,
    description: "A musical biography celebrating the life and legacy of Oliver Mutukudzi, Zimbabwe's beloved musician and cultural icon.",
    genre: "Music",
    genres: ["Music", "Documentary", "Diaspora"],
    year: 2023,
    rating: "PG",
    duration: "2h 8m",
    language: "Shona",
  },
  {
    id: "7",
    type: "series",
    title: "Ubuntu: Stories of Humanity",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: The Philosophy of Ubuntu",
        description: "Exploring the African philosophy that emphasizes our shared humanity.",
      },
      {
        title: "Episode 2: Community Healing",
        description: "How traditional African healing practices bring communities together.",
      },
      {
        title: "Episode 3: Modern Ubuntu",
        description: "Ubuntu principles in contemporary African leadership and business.",
      },
    ],
    description: "A philosophical journey through African wisdom and community values.",
    genre: "Lifestyle",
    genres: ["Lifestyle", "Documentary", "Diaspora"],
    year: 2023,
    rating: "TV-PG",
    duration: "6 eps",
    language: "English",
  },
  {
    id: "8",
    type: "movie",
    title: "Afrimation: The New Wave",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A groundbreaking animated film showcasing African folklore through cutting-edge animation techniques.",
    genre: "Afrimation",
    genres: ["Afrimation", "Kids", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 35m",
    language: "English",
  },
];

export const mockSeries = [
  {
    id: "1",
    title: "African Skies",
    thumbnail: "/thumnails/african_skies.jpeg",
    isPremium: false,
    description: "A breathtaking journey through Africa's diverse landscapes and cultures, exploring the beauty and challenges of life on the continent.",
    genre: "Documentary",
    genres: ["Documentary", "Travel", "Nature"],
    year: 2024,
    rating: "PG",
    duration: "1 season",
    episodes: [
      {
        title: "Episode 1: The Serengeti's Secrets",
        description: "Uncover the hidden wonders of the Serengeti, from the Great Migration to the Big Five.",
      },
      {
        title: "Episode 2: Victoria Falls - The Smoke That Thunders",
        description: "Explore the majesty of Victoria Falls and the Zambezi River.",
      },
      {
        title: "Episode 3: The Sahara's Enduring Spirit",
        description: "Experience the vastness of the Sahara Desert and its resilient inhabitants.",
      },
    ],
    crew: ["Director David Attenborough", "Producer National Geographic"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "2",
    title: "Nollywood Dreams",
    thumbnail: "/thumnails/nollywood_dreams.jpeg",
    isPremium: true,
    description: "Step into the vibrant world of Nollywood, the Nigerian film industry, and follow the lives of those who dare to dream.",
    genre: "Drama",
    genres: ["Drama", "Romance", "Platform Originals"],
    year: 2023,
    rating: "PG-13",
    duration: "1 season",
    episodes: [
      {
        title: "Episode 1: The Audition",
        description: "Aspiring actress faces challenges and triumphs during a high-stakes audition.",
      },
      {
        title: "Episode 2: Behind the Scenes",
        description: "A glimpse into the making of a Nollywood blockbuster.",
      },
      {
        title: "Episode 3: The Premiere",
        description: "The cast and crew prepare for the glamorous premiere of their film.",
      },
    ],
    crew: ["Director Kunle Afolayan", "Producer Mo Abudu"],
    ageLimit: "13+",
    language: "English",
  },
  {
    id: "3",
    title: "Shaka Zulu: The Series",
    thumbnail: "/thumnails/shaka_zulu.jpeg",
    isPremium: true,
    description: "A historical drama depicting the life and times of Shaka Zulu, the legendary king of the Zulu nation.",
    genre: "History",
    genres: ["History", "Drama", "War"],
    year: 2023,
    rating: "R",
    duration: "1 season",
    episodes: [
      {
        title: "Episode 1: The Rise of Shaka",
        description: "Shaka's early life and the unification of the Zulu tribes.",
      },
      {
        title: "Episode 2: The Warrior King",
        description: "Shaka's military strategies and battles that expanded the Zulu kingdom.",
      },
      {
        title: "Episode 3: The Legacy",
        description: "The enduring legacy of Shaka Zulu in modern South Africa.",
      },
    ],
    crew: ["Director John Trengove", "Producer Anant Singh"],
    ageLimit: "16+",
    language: "Zulu",
  },
  {
    id: "4",
    title: "Mama Africa: The Musical",
    thumbnail: "/thumnails/mama_africa.jpeg",
    isPremium: true,
    description: "A celebration of the life and music of Miriam Makeba, featuring her timeless songs and the story of her journey as an artist and activist.",
    genre: "Musical",
    genres: ["Musical", "Biography", "Drama"],
    year: 2023,
    rating: "PG",
    duration: "1 season",
    episodes: [
      {
        title: "Episode 1: The Voice of Africa",
        description: "Miriam's early years and the development of her unique musical style.",
      },
      {
        title: "Episode 2: Exile and Activism",
        description: "Miriam's life in exile and her activism against apartheid.",
      },
      {
        title: "Episode 3: Return to South Africa",
        description: "Miriam's triumphant return to a free South Africa and her enduring legacy.",
      },
    ],
    crew: ["Director Darrell Roodt", "Producer Anant Singh"],
    ageLimit: "All Ages",
    language: "English",
  },
];
