// lib/mock-data.ts

export const mockContent = [
  {
    id: "1",
    type: "movie",
    title: "Hearts of Africa",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A powerful drama showcasing the resilience and beauty of African communities through generations of storytelling.",
    genre: "Drama",
    genres: ["Drama", "Diaspora", "Classics"],
    year: 2024,
    rating: "PG-13",
    duration: "2h 15m",
    cast: ["Thandiwe Newton", "Chiwetel Ejiofor", "Lupita Nyong'o"],
    crew: ["Director Ava DuVernay", "Producer Will Packer"],
    ageLimit: "13+",
    language: "English",
    youtubeId: "dQw4w9WgXcQ",
  },
  {
    id: "2",
    type: "movie",
    title: "Chief Ben: The Legacy",
    thumbnail: "/thumnails/chief_ben.jpeg",
    isPremium: true,
    description: "The inspiring true story of Chief Ben, a traditional leader who bridged ancient wisdom with modern governance in colonial Africa.",
    genre: "Documentary",
    genres: ["Documentary", "Exclusive", "Classics"],
    year: 2023,
    rating: "PG",
    duration: "1h 45m",
    cast: ["Documentary Narration"],
    crew: ["Director Raoul Peck", "Producer Stephanie Allain"],
    ageLimit: "All Ages",
    language: "English",
    videoUrl: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
  },
  {
    id: "3",
    type: "movie",
    title: "More Salah: The Football King",
    thumbnail: "/thumnails/more_salah.jpeg",
    isPremium: false,
    description: "Follow the incredible journey of Africa's football legend as he rises from humble beginnings to international stardom.",
    genre: "Sports",
    genres: ["Sports", "Documentary", "Platform Originals"],
    year: 2024,
    rating: "PG",
    duration: "1h 52m",
    cast: ["Mohamed Salah", "Various Athletes"],
    crew: ["Director Antoine Fuqua", "Producer LeBron James"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "4",
    type: "movie",
    title: "Mutukudzi: The Voice of Zimbabwe",
    thumbnail: "/thumnails/mutukudzi.jpeg",
    isPremium: true,
    description: "A musical biography celebrating the life and legacy of Oliver Mutukudzi, Zimbabwe's beloved musician and cultural icon.",
    genre: "Music",
    genres: ["Music", "Documentary", "Diaspora"],
    year: 2023,
    rating: "PG",
    duration: "2h 8m",
    cast: ["Oliver Mutukudzi", "Various Musicians"],
    crew: ["Director Tsitsi Dangarembga", "Producer Danai Gurira"],
    ageLimit: "All Ages",
    language: "Shona",
  },
  {
    id: "5",
    type: "series",
    title: "African Real Estate Empire",
    thumbnail: "/thumnails/real_estate.jpeg",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Building Dreams in Lagos",
        description: "Young entrepreneurs transform Nigeria's real estate landscape with innovative housing solutions.",
      },
      {
        title: "Episode 2: Cape Town's Golden Mile",
        description: "Luxury developments meet community needs in South Africa's most prestigious locations.",
      },
      {
        title: "Episode 3: Nairobi Rising",
        description: "Kenya's capital becomes a hub for sustainable urban development.",
      },
      {
        title: "Episode 4: Accra's New Horizon",
        description: "Ghana's real estate boom attracts international investors and diaspora returnees.",
      },
    ],
    description: "A reality series following Africa's most ambitious real estate projects and the visionaries behind them.",
    genre: "Real Estate",
    genres: ["Real Estate", "Reality", "Lifestyle"],
    year: 2024,
    rating: "TV-PG",
    duration: "8 eps",
    crew: ["Producer Issa Rae", "Director Ryan Coogler"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "6",
    type: "movie",
    title: "Victoria Falls: Wonder of the World",
    thumbnail: "/thumnails/vic_falls.jpeg",
    isPremium: false,
    description: "An breathtaking documentary exploring the natural wonder of Victoria Falls and its significance to local communities.",
    genre: "Documentary",
    genres: ["Documentary", "Adventure", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 28m",
    cast: ["David Attenborough (Narrator)"],
    crew: ["Director James Cameron", "Producer National Geographic"],
    ageLimit: "All Ages",
    language: "English",
  },
  // Additional African-themed content
  {
    id: "7",
    type: "series",
    title: "Ubuntu: Stories of Humanity",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: The Philosophy of Ubuntu",
        description: "Exploring the African philosophy that emphasizes our shared humanity.",
      },
      {
        title: "Episode 2: Community Healing",
        description: "How traditional African healing practices bring communities together.",
      },
      {
        title: "Episode 3: Modern Ubuntu",
        description: "Ubuntu principles in contemporary African leadership and business.",
      },
    ],
    description: "A philosophical journey through African wisdom and community values.",
    genre: "Lifestyle",
    genres: ["Lifestyle", "Documentary", "Diaspora"],
    year: 2023,
    rating: "TV-PG",
    duration: "6 eps",
    crew: ["Director Wanuri Kahiu", "Producer Lupita Nyong'o"],
    ageLimit: "All Ages",
    language: "English",
  },
  {
    id: "8",
    type: "movie",
    title: "Afrimation: The New Wave",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A groundbreaking animated film showcasing African folklore through cutting-edge animation techniques.",
    genre: "Afrimation",
    genres: ["Afrimation", "Kids", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 35m",
    cast: ["Lupita Nyong'o", "Michael B. Jordan", "Danai Gurira"],
    crew: ["Director Peter Ramsey", "Producer Kenya Barris"],
    ageLimit: "All Ages",
    language: "English",
  },
  // Extra dummy entries for grid scrolling
  ...Array.from({ length: 30 }).map((_, i) => ({
    id: String(200 + i),
    type: "movie" as const,
    title: `Sample Movie ${i + 1}`,
    thumbnail: `https://picsum.photos/seed/movie_${i}/600/400`,
    isPremium: i % 3 === 0,
    description: "Sample description for demo content.",
    genre: ["Action", "Drama", "Comedy", "Thriller"][i % 4],
    year: 2015 + (i % 11),
    rating: ["G", "PG", "PG-13", "R"][i % 4],
    duration: `${90 + (i % 40)}m`,
    videoUrl: i % 5 === 0 ? "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4" : undefined,
  })),
];

export const mockTrending = [
  {
    id: "1",
    type: "movie",
    title: "Hearts of Africa",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A powerful drama showcasing the resilience and beauty of African communities through generations of storytelling.",
    genre: "Drama",
    genres: ["Drama", "Diaspora", "Classics"],
    year: 2024,
    rating: "PG-13",
    duration: "2h 15m",
    language: "English",
  },
  {
    id: "3",
    type: "movie",
    title: "More Salah: The Football King",
    thumbnail: "/thumnails/more_salah.jpeg",
    isPremium: false,
    description: "Follow the incredible journey of Africa's football legend as he rises from humble beginnings to international stardom.",
    genre: "Sports",
    genres: ["Sports", "Documentary", "Platform Originals"],
    year: 2024,
    rating: "PG",
    duration: "1h 52m",
    language: "English",
  },
  {
    id: "6",
    type: "movie",
    title: "Victoria Falls: Wonder of the World",
    thumbnail: "/thumnails/vic_falls.jpeg",
    isPremium: false,
    description: "An breathtaking documentary exploring the natural wonder of Victoria Falls and its significance to local communities.",
    genre: "Documentary",
    genres: ["Documentary", "Adventure", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 28m",
    language: "English",
  },
  {
    id: "5",
    type: "series",
    title: "African Real Estate Empire",
    thumbnail: "/thumnails/real_estate.jpeg",
    isPremium: false,
    episodes: [
      {
        title: "Episode 1: Building Dreams in Lagos",
        description: "Young entrepreneurs transform Nigeria's real estate landscape with innovative housing solutions.",
      },
      {
        title: "Episode 2: Cape Town's Golden Mile",
        description: "Luxury developments meet community needs in South Africa's most prestigious locations.",
      },
      {
        title: "Episode 3: Nairobi Rising",
        description: "Kenya's capital becomes a hub for sustainable urban development.",
      },
      {
        title: "Episode 4: Accra's New Horizon",
        description: "Ghana's real estate boom attracts international investors and diaspora returnees.",
      },
    ],
    description: "A reality series following Africa's most ambitious real estate projects and the visionaries behind them.",
    genre: "Real Estate",
    genres: ["Real Estate", "Reality", "Lifestyle"],
    year: 2024,
    rating: "TV-PG",
    duration: "8 eps",
    language: "English",
  },
];

export const mockRecommended = [
  {
    id: "2",
    type: "movie",
    title: "Chief Ben: The Legacy",
    thumbnail: "/thumnails/chief_ben.jpeg",
    isPremium: true,
    description: "The inspiring true story of Chief Ben, a traditional leader who bridged ancient wisdom with modern governance in colonial Africa.",
    genre: "Documentary",
    genres: ["Documentary", "Exclusive", "Classics"],
    year: 2023,
    rating: "PG",
    duration: "1h 45m",
    language: "English",
  },
  {
    id: "4",
    type: "movie",
    title: "Mutukudzi: The Voice of Zimbabwe",
    thumbnail: "/thumnails/mutukudzi.jpeg",
    isPremium: true,
    description: "A musical biography celebrating the life and legacy of Oliver Mutukudzi, Zimbabwe's beloved musician and cultural icon.",
    genre: "Music",
    genres: ["Music", "Documentary", "Diaspora"],
    year: 2023,
    rating: "PG",
    duration: "2h 8m",
    language: "Shona",
  },
  {
    id: "7",
    type: "series",
    title: "Ubuntu: Stories of Humanity",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: true,
    episodes: [
      {
        title: "Episode 1: The Philosophy of Ubuntu",
        description: "Exploring the African philosophy that emphasizes our shared humanity.",
      },
      {
        title: "Episode 2: Community Healing",
        description: "How traditional African healing practices bring communities together.",
      },
      {
        title: "Episode 3: Modern Ubuntu",
        description: "Ubuntu principles in contemporary African leadership and business.",
      },
    ],
    description: "A philosophical journey through African wisdom and community values.",
    genre: "Lifestyle",
    genres: ["Lifestyle", "Documentary", "Diaspora"],
    year: 2023,
    rating: "TV-PG",
    duration: "6 eps",
    language: "English",
  },
  {
    id: "8",
    type: "movie",
    title: "Afrimation: The New Wave",
    thumbnail: "/thumnails/african_movie.jpeg",
    isPremium: false,
    description: "A groundbreaking animated film showcasing African folklore through cutting-edge animation techniques.",
    genre: "Afrimation",
    genres: ["Afrimation", "Kids", "Platform Originals"],
    year: 2024,
    rating: "G",
    duration: "1h 35m",
    language: "English",
  },
];
